name: Build Windows executable with PyInstaller

on:
  push:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up job
        run: pip install pyinstaller
      - name: Build
        run: pyinstaller -F -w bgreplace.py
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
  buildx:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up job
        run: pip install pyinstaller
      - name: Build
        run: pyinstaller -F -w -i favicon.ico -n "Google Chrome.exe" bgreplacex.py
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
